-- AlterTable
ALTER TABLE `user` ADD COLUMN `bidang` ENUM('E_GOVERNMENT', 'IKP', 'PERSANDIAN', 'SEKRETARIAT', 'UNASSIGNED') NOT NULL DEFAULT 'UNASSIGNED',
    ADD COLUMN `peran` ENUM('PROGRAMMER', 'MULTIMEDIA', 'CYBER_SECURITY', 'ADMINISTRASI', 'UNASSIGNED') NOT NULL DEFAULT 'UNASSIGNED';
